default_context:
  author_name: "Roberto Vera Alvarez"
  user_email: "veraalva@ncbi.nlm.nih.gov"
  project_name: "nopal-transcriptome"
  dataset_name: "PRJNA320545"
  scientific_name: "Opuntia streptacantha"
  sequencing_technology: "paired-end"
  kingdom: "viridiplantae"